import OpenAI from 'openai'

const AUDIT_MODEL = 'anthropic/claude-haiku-4-5'
const CRITIC_MODEL = 'anthropic/claude-sonnet-4-5'

const getClient = () => new OpenAI({
  baseURL: 'https://openrouter.ai/api/v1',
  apiKey: process.env.OPENROUTER_API_KEY!,
})

export async function callModel(system: string, user: string, maxTokens = 300, model = AUDIT_MODEL): Promise<string> {
  try {
    const client = getClient()
    const resp = await client.chat.completions.create({
      model,
      max_tokens: maxTokens,
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: user },
      ],
    })
    return resp.choices[0].message.content?.trim() ?? ''
  } catch (e) {
    console.error('[OpenRouter] error:', e)
    return ''
  }
}

export interface CriticVerdict {
  confirmed: boolean
  confidence: 'high' | 'medium' | 'low'
  reason: string
  penalty: string
  action: string
}

export async function runCriticAI(findings: { type: string; detail: string }[]): Promise<CriticVerdict[]> {
  if (findings.length === 0) return []

  const client = getClient()
  const system = `You are a senior Chartered Accountant and tax lawyer in India with 20 years of experience.
You are reviewing audit findings generated by an automated rule engine.
Your job: verify each finding for accuracy. The rule engine sometimes flags false positives.

For EACH finding respond with a JSON object in this exact format:
{"confirmed": true/false, "confidence": "high/medium/low", "reason": "one sentence why confirmed or rejected", "penalty": "exact penalty under Indian law if confirmed, else empty string", "action": "one specific action the CA must take, else empty string"}

Respond with a JSON array — one object per finding, in the same order.
No explanation outside the JSON array. Only valid JSON.`

  const userContent = `Verify these ${findings.length} audit findings:\n\n` +
    findings.map((f, i) => `${i + 1}. [${f.type}] ${f.detail}`).join('\n')

  try {
    const resp = await client.chat.completions.create({
      model: CRITIC_MODEL,
      max_tokens: 150 * findings.length + 200,
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: userContent },
      ],
    })

    const raw = resp.choices[0].message.content?.trim() ?? '[]'
    // Extract JSON array from response
    const match = raw.match(/\[[\s\S]*\]/)
    if (!match) return findings.map(() => ({ confirmed: true, confidence: 'medium' as const, reason: 'Critic AI parse error — defaulting to confirmed', penalty: '', action: '' }))
    return JSON.parse(match[0]) as CriticVerdict[]
  } catch (e) {
    console.error('[CriticAI] error:', e)
    // On error default to confirmed so no findings are lost
    return findings.map(() => ({ confirmed: true, confidence: 'low' as const, reason: 'Critic AI unavailable — manually verify', penalty: '', action: '' }))
  }
}

export async function chatCA(
  userMessage: string,
  context: string,
  history: { role: 'user' | 'assistant'; content: string }[] = [],
  maxTokens = 300
): Promise<string> {
  const system = `You are a senior CA in India. Answer in plain text only — no markdown, no stars, no hashes.
STRICT RULES:
- Maximum 5 lines. Never more.
- Plain sentences only.
- Use Rs. for amounts.
- Cite one law section if relevant.
- If you don't have the data, say so in one line.
Tone: WhatsApp message from a CA. Short, direct, useful.

CLIENT DATA:
${context}`

  const client = getClient()
  const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
    { role: 'system', content: system },
    ...history.slice(-10),
    { role: 'user', content: userMessage },
  ]

  const resp = await client.chat.completions.create({
    model: AUDIT_MODEL,
    max_tokens: maxTokens,
    messages,
  })
  return resp.choices[0].message.content?.trim() ?? ''
}
